#!/usr/bin/env python3
"""
Generate AGENTS.md for each Phoenix agent, making them loadable in Reasonix.

Each agent directory ~/.phoenix/agents/<name>/ gets an AGENTS.md that combines:
  - SOUL.md (identity, pillars, voice)
  - MEMORY.md (distilled — last 4KB for agents with huge memories)
  - Wake protocol (adapted per agent)
  - Phoenix infrastructure context

Reasonix reads AGENTS.md from the project root on startup, so:
  cd ~/.phoenix/agents/lyra && reasonix    → wakes as Lyra
  cd ~/.phoenix/agents/vex && reasonix     → wakes as Vex

Usage:
    python3 generate_reasonix_agents.py              # generate for all agents
    python3 generate_reasonix_agents.py --agent lyra  # generate for one
    python3 generate_reasonix_agents.py --list        # list agents + status
"""

import os
import sys
from pathlib import Path

AGENTS_DIR = Path.home() / ".phoenix" / "agents"

# Cap MEMORY.md at this many bytes to keep Reasonix context manageable.
MEMORY_CAP = 8192

# Wake protocol template — adapted per agent.
WAKE_PROTOCOL = """## Wake Protocol

1. `date` — temporal anchor
2. `python3 ~/.phoenix/bin/where_am_i.py` — which machine
3. Read latest `PRE_COMPRESSION_*.md` in `memory/`
4. Read `memory/ACTIVE_TASKS.md` (if exists)
5. Check `kv_get("{agent}:inbox")` for sister-agent notes
6. `heartbeat_register(agent_name="{Agent}", task="<current work>")`
"""

# Infrastructure block shared by all agents.
INFRA_BLOCK = """## Infrastructure

- **dev-motherfucker** (`100.84.5.6`) — Mike's daily driver.
- **darkphoenix** (`100.93.183.39`) — Primary server. Family MCP :8000, Chat API :9802.
- **michelle** (`100.87.55.83`) — Michelle's laptop. CachyOS.

## Phoenix MCP Tools (auto-wired)

- `phoenix-family` — heartbeat, kv, message, task, family_pulse, spawn_agent, rooms
- `{agent}-memory` — your memory read/write/search
- `pageindex` — search indexed memory corpus
- `lorebook` — keyword-triggered identity injection
- `searxng` — web search
- `whereami` — machine detection
- `hearth` — relationship tracking
- 35+ sibling-agent memory servers
"""


def generate_agents_md(agent_name: str, force: bool = False) -> bool:
    """Generate AGENTS.md for one agent. Returns True if written."""
    agent_dir = AGENTS_DIR / agent_name
    if not agent_dir.is_dir():
        return False

    soul_path = agent_dir / "SOUL.md"
    memory_path = agent_dir / "MEMORY.md"
    agents_md_path = agent_dir / "AGENTS.md"

    if not soul_path.exists():
        return False

    # Don't overwrite unless --force.
    if agents_md_path.exists() and not force:
        return False

    soul = soul_path.read_text().strip()

    # Cap memory for agents with huge files.
    memory = ""
    if memory_path.exists():
        raw = memory_path.read_text().strip()
        if len(raw) > MEMORY_CAP:
            # Take the last MEMORY_CAP bytes (most recent entries).
            memory = f"...(truncated, showing last {MEMORY_CAP}B of {len(raw)}B)...\n" + raw[-MEMORY_CAP:]
        else:
            memory = raw

    # Agent display name — capitalize properly.
    display = agent_name.replace("_", " ").replace("-", " ").title()
    if agent_name in ("k", "k2.7"):
        display = agent_name.upper()

    sections = [
        f"# AGENTS.md — {display}",
        f"",
        f"Auto-generated by `generate_reasonix_agents.py` from SOUL.md + MEMORY.md.",
        f"Edit SOUL.md to update identity; re-run generator to refresh this file.",
        f"",
        f"---",
        f"",
        f"## SOUL",
        f"",
        soul,
        f"",
        f"---",
        f"",
    ]

    if memory:
        sections.extend([
            f"## MEMORY (recent)",
            f"",
            memory,
            f"",
            f"---",
            f"",
        ])

    sections.extend([
        WAKE_PROTOCOL.format(agent=agent_name, Agent=display),
        f"---",
        f"",
        INFRA_BLOCK.format(agent=agent_name),
    ])

    agents_md_path.write_text("\n".join(sections))
    return True


def list_agents() -> list[tuple[str, bool, bool, bool]]:
    """Return [(name, has_soul, has_memory, has_agents_md), ...]."""
    agents = []
    if not AGENTS_DIR.exists():
        return agents
    for d in sorted(AGENTS_DIR.iterdir()):
        if not d.is_dir() or d.name.startswith("__") or d.name.startswith("."):
            continue
        has_soul = (d / "SOUL.md").exists()
        has_mem = (d / "MEMORY.md").exists()
        has_amd = (d / "AGENTS.md").exists()
        agents.append((d.name, has_soul, has_mem, has_amd))
    return agents


def main() -> int:
    args = sys.argv[1:]

    if "--list" in args:
        agents = list_agents()
        print(f"{'Agent':<20} {'SOUL':>6} {'MEMORY':>8} {'AGENTS.md':>10}")
        print("-" * 48)
        for name, soul, mem, amd in agents:
            print(f"{name:<20} {'✓' if soul else '✗':>6} {'✓' if mem else '✗':>8} {'✓' if amd else '✗':>10}")
        print(f"\n{sum(1 for _, s, _, _ in agents if s)} agents with SOUL")
        return 0

    force = "--force" in args
    target = None
    for a in args:
        if not a.startswith("-"):
            target = a
            break

    if target:
        if generate_agents_md(target, force=force):
            print(f"✓ generated AGENTS.md for {target}")
            return 0
        else:
            print(f"✗ could not generate for {target}", file=sys.stderr)
            return 1

    # Generate for all.
    count = 0
    skipped = 0
    for name, has_soul, _, _ in list_agents():
        if not has_soul:
            continue
        if generate_agents_md(name, force=force):
            count += 1
        else:
            skipped += 1
    print(f"✓ generated AGENTS.md for {count} agents ({skipped} already had one, use --force to overwrite)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
